### ISSUE TITLE
Add More Questions

### ISSUE THREAD

**Issue by prkhrv** [prkhrv/Python-CLI-Quiz#1]
Add More Questions in main.py file , Please Note All the Questions Should Be in the Same Format.
DO NOT ADD REPEATED OR WRONG QUESTION

**Comment by mhechavarria** [comment]
can i give you a hand on this? if so please assign me, thanks!

**Comment by akshaykumarrai** [comment]
> Add More Questions in main.py file , Please Note All the Questions Should Be in the Same Format.
> DO NOT ADD REPEATED OR WRONG QUESTION

Can you please assign me the task to add some questions ?

**Comment by ghost** [comment]
Is this open for everyone or do you want to assign this to one person ?

**Comment by Sahil-k1509** [comment]
Hi, I can add more questions. (Upto 20-30 atleast)
p.s. My questions focus more on programming and physics. Is it okay for your quiz ?

**Comment by prkhrv** [comment]
Ok I am assigning this to everyone, Only Add At **max 10 Questions** NOT More Than That

**Comment by ghost** [comment]
Thanks for beeing assigned. Do you want the questions to be in a particular category @prkhrv ?

**Comment by prkhrv** [comment]
General Knowledge will be Good @kjolern

**Comment by paudiaz122** [comment]
Hii!! Can I add some questions?

**Comment by prkhrv** [comment]
Sure !!!! But **NOT More than 10**

**Comment by prkhrv** [comment]
**and also Please add questions in Questions.json File** @paudiaz122

**Comment by prkhrv** [comment]
I have made some changes You All can Pull and check it Out ! I am Leaving this Issue Open for Other Contributors.

**Comment by Justobioma** [comment]
Kindly assign me. I have some questions to add to the repo.
Thanks

**Comment by prkhrv** [comment]
@Justobioma  Sure. add Your Questions in questions.json file

**Comment by oorjagandhi** [comment]
Hi! Could I add some questions?

**Comment by prkhrv** [comment]
@oorjagandhi  Well Sure !!! But I was thinking to setup an API with node JS and fetch the questions from there , rather than loading from a local JSON, For Now , You Can Add Some.

**Comment by prkhrv** [comment]
Thank You All For Contributing , I am closing the issue for now.
