### ISSUE TITLE
Update Readme.md With a Good Explanation about code with snippets

### ISSUE THREAD

**Issue by prkhrv** [prkhrv/Python-CLI-Quiz#12]

**Comment by aayushivaish** [comment]
on It !!!

**Comment by Abhiramborige** [comment]
Can i make some logic changes for smooth running of quiz and make a good readme..

And also, add label, hactoberfest-accepted, according to guidelines.

**Comment by Abhiramborige** [comment]
Can I ???

**Comment by prkhrv** [comment]
@Abhiramborige If the assigned person is unable to send a pull request in 24 hours. I will assign it to you
