### ISSUE TITLE
Chalk function not changing colour

### ISSUE THREAD

**Issue by Sahil-k1509** [prkhrv/Python-CLI-Quiz#8]
I installed simple-chalk and ran the program, but the output is being shown like this:
>[31mWrong!! The Correct Answer is Washington DC[0m    

Instead of being in yellow/red/cyan colour. I faced this issue in my pokemon game too
when I was using termcolor library. I had to **import colorama** and use _colorama.init()_
to initialize termcolor's functions. Do we need to do same for simple-chalk as well?

**Comment by prkhrv** [comment]
Its Working Pretty good on My system. I will Look into This For sure, Thanks For Rasing the issue.

**Comment by Abhiramborige** [comment]
Hey can i make some logic changes

**Comment by Sahil-k1509** [comment]
> Hey can i make some logic changes

Please elaborate more about the changes. I am curious

**Comment by prkhrv** [comment]
@Sahil-k1509  Let me know if this issue Persists and what Environment you are using? .

**Comment by Sahil-k1509** [comment]
> @Sahil-k1509 Let me know if this issue Persists and what Environment you are using? .

I am on windows using python 3.8.1(No virtual environment)
